repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        files: ^(ts_diffusion/|tests/)
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language: python
      args:
        - "--line-length=88"
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3'  # add version here
    hooks:
      - id: poetry-check
      # - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
